### ISSUE TITLE
Submit plugin to Matrix branch

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-addon-soundcloud#42]
According to https://forum.kodi.tv/showthread.php?tid=351745, plugins will only be available in Kodi v19 if they

* bump the xbmc.python dependency to 3.0.0 in the addon.xml file
* are re-submitted to the Matrix branch

### TODO

* [x] Create a Krypton branch to be able to backport fixes
* [x] Add a Matrix bagde to the README
* [x] Strip Python 2 compatibility stuff (script.module.future)
* [x] Use new settings format (https://kodi.wiki/view/Add-on_settings_conversion)
* [x] Use `with` syntax for files: https://github.com/xbmc/xbmc/commit/0775d520a166e07322ffdd092d5c8e2758b1ddc2
* [x] Remove `future` package from Pipfile, update Python requirement to 3.6 and update README accordingly
* [x] Add Python 3.6 and 3.9 to test matrix
* [x] Submit plugin to the Matrix branch
* [ ] Create a new release

**Comment by rikardfries** [comment]
Hi,
there is soon a beta of Matrix.
What are your thoughts on this one ?
Do you need help to test this ?

**Comment by jaylinski** [comment]
Thanks for the reminder. I'll try to resolve this issue this week (I hope I'll find the time). Since the plugin already works on Matrix, there shouldn't be much to test.
